In [1]:
import data
import eval
import model
import preprocess
import postprocess

Data length:  200
Data length:  115
Data length:  200
Labels length: 200
Labels length: 115
Labels length: 200


/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import TfidfVectorizer

first load the data set, and save it as a csv?

In [3]:
df = data.load_data()
print(df)
df.to_csv("./data.csv")
dom_mlb, sub_mlb, dom_narr_enc, sub_narr_enc = preprocess.encode_labels(df)

Data length:  200
Data length:  115
Data length:  200
Labels length: 200
Labels length: 115
Labels length: 200
                   id                                               text  \
0    EN_UA_104876.txt  Putin honours army unit blamed for Bucha massa...   
1    EN_UA_023211.txt  Europe Putin thanks US journalist Tucker Carls...   
2    EN_UA_011260.txt  Russia has a clear plan to resolve the conflic...   
3    EN_UA_101067.txt  First war of TikTok era sees tragedy, humor an...   
4    EN_UA_102963.txt  Ukraine's President Zelenskyy to address Mexic...   
..                ...                                                ...   
510        PT_157.txt  Reino Unido: o país foi invadido por uma nova ...   
511        PT_143.txt  "O combate às alterações climáticas não está n...   
512         PT_89.txt  UE retira reunião de ministros dos Negócios Es...   
513         PT_62.txt  As novas fogueiras da Inquisição\n\n1. O reito...   
514         PT_76.txt  Rússia está a desistir de Khar

Train it on the sub classes

In [4]:
vec = TfidfVectorizer(min_df=0.02,max_df=0.8)
X = vec.fit_transform(df.text)
y = sub_narr_enc

In [5]:
y_pred, y_true = model.logistic_regression_loocv(X,y,majority_ensemble=True)
print(classification_report(y_true = y_true, y_pred=y_pred, target_names=sub_mlb.classes_))

Skipped fold 17, labels invalid
Skipped fold 89, labels invalid
Skipped fold 154, labels invalid
Skipped fold 165, labels invalid
Skipped fold 178, labels invalid
Skipped fold 225, labels invalid
Skipped fold 316, labels invalid
Skipped fold 459, labels invalid
Skipped fold 499, labels invalid
Predicted Labels:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
True Labels:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
                                                                                                            precision    recall  f1-score   support

                                 CC: Amplifying Climate Fears: Amplifying existing fears of global warming       0.49      0.93      0.64        41
                                               CC: Amplifying Climate Fears: Doomsday scenarios for humans       0.22      0.64      0.

/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Trained on the dom classes:

In [6]:
y = dom_narr_enc
y_pred, y_true = model.logistic_regression_loocv(X,y,majority_ensemble=True)
print(classification_report(y_true = y_true, y_pred=y_pred, target_names=dom_mlb.classes_))

Skipped fold 165, labels invalid
Predicted Labels:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]]
True Labels:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]]
                                                        precision    recall  f1-score   support

                          CC: Amplifying Climate Fears       0.60      0.92      0.72        64
                      CC: Climate change is beneficial       0.00      0.00      0.00         2
              CC: Controversy about green technologies       0.20      0.25      0.22         8
                     CC: Criticism of climate movement       0.43      0.71      0.54        21
                     CC: Criticism of climate policies       0.20      0.52      0.29        29
         CC: Criticism of institutions and authorities       0.41      0.84      0.55        49
                     

/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
