In [1]:
import data
import eval
import model
import preprocess
import postprocess

/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.25.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import TfidfVectorizer

First off, the steps taken to fully load in the data set.

Step 1: load the raw text files and their id's into a dataframe

Step 2: if the texts are not in English, translate them

Step 3: concatenate the text files into a single dataset

Step 4: load in the labels

Step 5: merge the text and labels data sets


In [3]:
# load english text data
# df_text_en = data.load_text_data("/Users/jochem/Documents/school/Uni KI jaar 4/Scriptie/Train Data/training_data_16_October_release/EN/raw-documents")

# load and translate hindi text
df_text_hi = data.load_text_data("/Users/jochem/Documents/school/Uni KI jaar 4/Scriptie/Train Data/training_data_16_October_release/HI/raw-documents")
preprocess.translate(df_text_hi, source_lang="hi")

# df_text_pt = load_text_data("/Users/jochem/Documents/school/Uni KI jaar 4/Scriptie/Train Data/training_data_16_October_release/PT/raw-documents")
# df_text = pd.concat([df_text_en, df_text_hi, df_text_pt])

# df_labels_en = load_labels("/Users/jochem/Documents/school/Uni KI jaar 4/Scriptie/Train Data/training_data_16_October_release/EN/subtask-2-annotations.txt")
# df_labels_hi = load_labels("/Users/jochem/Documents/school/Uni KI jaar 4/Scriptie/Train Data/training_data_16_October_release/HI/subtask-2-annotations.txt")
# df_labels_pt = load_labels("/Users/jochem/Documents/school/Uni KI jaar 4/Scriptie/Train Data/training_data_16_October_release/PT/subtask-2-annotations.txt")
# df_labels = pd.concat([df_labels_en, df_labels_hi, df_labels_pt])

# df_merged = pd.merge(df_text, df_labels, on="id")

Data length:  115


NotValidLength: 'पापा ने वॉर रुकवा दी' से लेकर ग्लोबल पीसमेकर तक, जानिए कैसे रूस और ...

'पापा ने वॉर रुकवा दी' से लेकर ग्लोबल पीसमेकर तक, जानिए कैसे रूस और यूक्रेन के बीच संतुलन बना रहे पीएम मोदी?
By मनाली रस्तोगी | Published: August 30, 2024 07:25 AM2024-08-30T07:25:07+5:302024-08-30T07:41:48+5:30
रूस और यूक्रेन दोनों के साथ भारत के ऐतिहासिक संबंधों के साथ मिलकर इस संतुलन अधिनियम ने इन अशांत समय में शांतिदूत के रूप में पीएम मोदी की क्षमता के बारे में उम्मीदें जगाई हैं। वह सही तरीके से कार्ड खेल रहे हैं।
रूस और यूक्रेन के बीच चल रहे संघर्ष के बीच प्रधानमंत्री नरेंद्र मोदी की कूटनीतिक चाल ने भारत को वैश्विक मंच पर एक महत्वपूर्ण खिलाड़ी के रूप में स्थापित किया है। मोदी की हालिया यूक्रेन यात्रा, जो तीन दशकों में किसी भारतीय प्रधान मंत्री की पहली यात्रा है, ने न केवल भारत में चर्चा को फिर से शुरू कर दिया है, बल्कि परस्पर विरोधी वैश्विक शक्तियों के बीच एक नाजुक संतुलन बनाए रखने की उनकी क्षमता का भी प्रदर्शन किया है।
रूस और यूक्रेन दोनों के साथ भारत के ऐतिहासिक संबंधों के साथ मिलकर इस संतुलन अधिनियम ने इन अशांत समय में शांतिदूत के रूप में पीएम मोदी की क्षमता के बारे में उम्मीदें जगाई हैं। वह सही तरीके से कार्ड खेल रहे हैं। चाहे वह भारत द्वारा आयोजित जी20 शिखर सम्मेलन हो, या छह सप्ताह के अंतराल में रूस और यूक्रेन दोनों की लगभग बैक-टू-बैक यात्राएं हों।
कूटनीतिक रणनीति
रूस के साथ भारत के संबंध शीत युद्ध के युग से हैं जब सोवियत संघ एक दृढ़ सहयोगी था। 1971 में हस्ताक्षरित शांति, मित्रता और सहयोग की भारत-सोवियत संधि दोनों देशों के बीच गहरे संबंधों का प्रमाण है।
रूस एक महत्वपूर्ण रक्षा भागीदार रहा है, जो दशकों से भारत को सैन्य उपकरण और प्रौद्योगिकी की आपूर्ति कर रहा है। दूसरी ओर, सोवियत संघ से स्वतंत्रता प्राप्त करने के बाद यूक्रेन भी भारत के लिए एक महत्वपूर्ण भागीदार रहा है, खासकर रक्षा, शिक्षा और कृषि जैसे क्षेत्रों में।
रूस-यूक्रेन संघर्ष के दौरान इन रिश्तों को निभाना एक कठिन चुनौती रही है। जबकि अमेरिका के नेतृत्व में पश्चिम ने देशों पर रूस के खिलाफ रुख अपनाने के लिए दबाव डाला है, वहीं भारत ने बातचीत और शांति की वकालत करते हुए तटस्थ रुख बनाए रखा है।
मोदी सरकार ने रूस और यूक्रेन दोनों के साथ बातचीत जारी रखी है और रूस को अलग-थलग करने के अंतरराष्ट्रीय दबाव के आगे झुकने से इनकार कर दिया है। इसका उदाहरण पश्चिमी प्रतिबंधों के बावजूद कच्चे तेल की खरीद सहित रूस के साथ भारत के चल रहे व्यापारिक सौदे हैं।
मोदी की यूक्रेन यात्रा प्रतीकात्मक थी, जो शांति के प्रति भारत की प्रतिबद्धता और इसमें शामिल सभी पक्षों के साथ जुड़ने की इच्छा का संकेत देती है। रूस और यूक्रेन दोनों में उन्हें जो स्वागत मिला, वह एक ऐसे राष्ट्र के रूप में भारत की अद्वितीय स्थिति को उजागर करता है जो पूर्व और पश्चिम के बीच की खाई को पाट सकता है। यह तथ्य कि मोदी दोनों देशों में इतना गर्मजोशी से स्वागत करने में कामयाब रहे, यह अंतरराष्ट्रीय मंच पर उनके सम्मान को उजागर करता है।
सोशल मीडिया पर वायरल हो रहा है 'पापा ने वार रुकवा दी'
भारत में मोदी की यूक्रेन यात्रा से सोशल मीडिया पर टिप्पणियों की लहर दौड़ गई है। 'पापा ने वार रुकवा दी' वाक्यांश, जो लोकसभा चुनाव के दौरान उत्पन्न हुआ था, इस बार एक अलग स्वर के साथ फिर से सामने आया है।
मोदी के समर्थकों ने उनके कूटनीतिक प्रयासों की प्रशंसा करने के लिए एक्स जैसे मंच का सहारा लिया है, ऐसी टिप्पणियों के साथ कि "मोदी जी वास्तव में एक वैश्विक नेता हैं" और "शांतिदूत के रूप में भारत की स्थिति अब मजबूत हो गई है"।
हालांकि, आलोचक संशय में हैं। कुछ लोगों ने सवाल किया है कि क्या मोदी की यात्रा का ज़मीनी स्तर पर कोई ठोस प्रभाव पड़ेगा, "क्या यह यात्रा सिर्फ एक पीआर अभ्यास है?" और "भारत शांति स्थापित करने के लिए क्या ठोस कदम उठा रहा है?"
लेकिन एक बात स्पष्ट है। पीएम मोदी ने जो कर दिखाया, कोई अन्य राष्ट्र प्रमुख नहीं कर पाया। और वो है- महज कुछ हफ्तों के अंतराल में पुतिन और ज़ेलेंस्की दोनों से मुलाकात। यह वैश्विक शांति निर्माता के रूप में भारत की भूमिका और स्थिति को मजबूत करता है।
शांति करने वाला
रूस और यूक्रेन दोनों के साथ जुड़ने के मोदी के प्रयास और बातचीत और शांति पर उनका जोर भारत को संघर्ष में संभावित मध्यस्थ के रूप में स्थापित कर सकता है। भारत की ऐतिहासिक गुटनिरपेक्ष नीति, तटस्थता के वर्तमान रुख के साथ मिलकर, इसे मध्यस्थ के रूप में कार्य करने के लिए आवश्यक विश्वसनीयता प्रदान करती है।
इसके अलावा वैश्विक मंच पर भारत के बढ़ते प्रभाव और रूस और यूक्रेन दोनों के नेताओं के साथ मोदी के व्यक्तिगत तालमेल से भारत दोनों पक्षों को बातचीत की मेज पर लाने में रचनात्मक भूमिका निभा सकता है।
भारत की सामरिक स्वतंत्रता
मोदी के दृष्टिकोण में जो बात विशेष रूप से प्रभावशाली है वह रणनीतिक स्वतंत्रता बनाए रखने की उनकी क्षमता है। रूस के साथ भारत के घनिष्ठ संबंधों और उसकी आर्थिक व्यस्तताओं के बावजूद, मोदी संयुक्त राज्य अमेरिका की अच्छी किताबों में बने रहने में कामयाब रहे हैं।
वर्तमान भू-राजनीतिक माहौल को देखते हुए, यह संतुलन कार्य कोई छोटी उपलब्धि नहीं है, जहां एक शक्ति के साथ बहुत निकटता से जुड़ना अक्सर दूसरों से अलगाव की ओर ले जाता है। मोदी की कूटनीति ने भारत को अपनी संप्रभुता का दावा करने और पूर्व बनाम पश्चिम के द्विआधारी संघर्ष में शामिल हुए बिना अपने राष्ट्रीय हितों को आगे बढ़ाने की अनुमति दी है।
विपक्ष चुप हो गया
दिलचस्प बात यह है कि जहां मोदी की यात्रा ने व्यापक ध्यान आकर्षित किया है, वहीं विपक्ष, विशेषकर कांग्रेस, काफी हद तक चुप रही है। यह चुप्पी उल्लेखनीय है, विशेषकर लोकसभा चुनाव के दौरान विपक्ष द्वारा "पापा ने वार रुकवा दी" तंज के साथ अपनाए गए आक्रामक रुख को देखते हुए।
कांग्रेस की ओर से प्रतिक्रिया की कमी इस बात का संकेत हो सकती है कि मोदी जिस कूटनीतिक रस्सी पर चल रहे हैं, उसकी मान्यता है, जिसकी आलोचना भारत की वैश्विक स्थिति के प्रति गैर-देशभक्त या गैर-समर्थक दिखाई दिए बिना करना मुश्किल है। --> Text length need to be between 0 and 5000 characters

first load the data set, and save it as a csv?

In [3]:
df = data.load_data()
print(df)
df.to_csv("./data.csv")
dom_mlb, sub_mlb, dom_narr_enc, sub_narr_enc = preprocess.encode_labels(df)

Data length:  200
Data length:  115
Data length:  200
Labels length: 200
Labels length: 115
Labels length: 200
                   id                                               text  \
0    EN_UA_104876.txt  Putin honours army unit blamed for Bucha massa...   
1    EN_UA_023211.txt  Europe Putin thanks US journalist Tucker Carls...   
2    EN_UA_011260.txt  Russia has a clear plan to resolve the conflic...   
3    EN_UA_101067.txt  First war of TikTok era sees tragedy, humor an...   
4    EN_UA_102963.txt  Ukraine's President Zelenskyy to address Mexic...   
..                ...                                                ...   
510        PT_157.txt  Reino Unido: o país foi invadido por uma nova ...   
511        PT_143.txt  "O combate às alterações climáticas não está n...   
512         PT_89.txt  UE retira reunião de ministros dos Negócios Es...   
513         PT_62.txt  As novas fogueiras da Inquisição\n\n1. O reito...   
514         PT_76.txt  Rússia está a desistir de Khar

Train it on the sub classes

In [4]:
vec = TfidfVectorizer(min_df=0.02,max_df=0.8)
X = vec.fit_transform(df.text)
y = sub_narr_enc

In [5]:
y_pred, y_true = model.logistic_regression_loocv(X,y,majority_ensemble=True)
print(classification_report(y_true = y_true, y_pred=y_pred, target_names=sub_mlb.classes_))

Skipped fold 17, labels invalid
Skipped fold 89, labels invalid
Skipped fold 154, labels invalid
Skipped fold 165, labels invalid
Skipped fold 178, labels invalid
Skipped fold 225, labels invalid
Skipped fold 316, labels invalid
Skipped fold 459, labels invalid
Skipped fold 499, labels invalid
Predicted Labels:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
True Labels:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
                                                                                                            precision    recall  f1-score   support

                                 CC: Amplifying Climate Fears: Amplifying existing fears of global warming       0.49      0.93      0.64        41
                                               CC: Amplifying Climate Fears: Doomsday scenarios for humans       0.22      0.64      0.

/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Trained on the dom classes:

In [6]:
y = dom_narr_enc
y_pred, y_true = model.logistic_regression_loocv(X,y,majority_ensemble=True)
print(classification_report(y_true = y_true, y_pred=y_pred, target_names=dom_mlb.classes_))

Skipped fold 165, labels invalid
Predicted Labels:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]]
True Labels:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]]
                                                        precision    recall  f1-score   support

                          CC: Amplifying Climate Fears       0.60      0.92      0.72        64
                      CC: Climate change is beneficial       0.00      0.00      0.00         2
              CC: Controversy about green technologies       0.20      0.25      0.22         8
                     CC: Criticism of climate movement       0.43      0.71      0.54        21
                     CC: Criticism of climate policies       0.20      0.52      0.29        29
         CC: Criticism of institutions and authorities       0.41      0.84      0.55        49
                     

/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
