In [1]:
import sys
sys.path.append("../src")
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score, make_scorer
from sklearn.svm import SVC

from pipeline import Pipeline
from model import SVM
from preprocess import Preprocessor
from postprocess import Postprocessor

In [2]:
model = SVM(kernel = "rbf", C=1.6, class_weight ="balanced")
preprocess = Preprocessor()
preprocess.embed()
preprocess.split()

In [3]:
pipeline = Pipeline(model=model, preprocessor=preprocess)

In [4]:
pipeline.run()

/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator MultiLabelBinarizer from version 1.5.1 when using version 1.1.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


PREPROCESSED THE DATA
TRAINING THE MODEL
FIT THE DATA
MAKING PREDICTIONS
COMPLETED PREDICTIONS
[[[290  11]
  [  3  36]]

 [[326   6]
  [  4   4]]

 [[332   3]
  [  3   2]]

 [[305  12]
  [  6  17]]

 [[335   0]
  [  4   1]]

 [[339   0]
  [  1   0]]

 [[340   0]
  [  0   0]]

 [[338   0]
  [  2   0]]

 [[335   0]
  [  5   0]]

 [[338   0]
  [  0   2]]

 [[339   0]
  [  1   0]]

 [[336   0]
  [  3   1]]

 [[338   0]
  [  2   0]]

 [[335   2]
  [  2   1]]

 [[337   1]
  [  1   1]]

 [[335   0]
  [  3   2]]

 [[329   2]
  [  8   1]]

 [[337   2]
  [  0   1]]

 [[330   3]
  [  5   2]]

 [[331   1]
  [  8   0]]

 [[334   3]
  [  2   1]]

 [[314  13]
  [  8   5]]

 [[317   8]
  [  8   7]]

 [[340   0]
  [  0   0]]

 [[336   1]
  [  3   0]]

 [[340   0]
  [  0   0]]

 [[337   2]
  [  1   0]]

 [[340   0]
  [  0   0]]

 [[338   2]
  [  0   0]]

 [[340   0]
  [  0   0]]

 [[337   0]
  [  2   1]]

 [[340   0]
  [  0   0]]

 [[340   0]
  [  0   0]]

 [[338   2]
  [  0   0]]

 [[340   0]
  [  0   

/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator MultiLabelBinarizer from version 1.5.1 when using version 1.1.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


[[[290  11]
  [  3  36]]

 [[326   6]
  [  4   4]]

 [[332   3]
  [  3   2]]

 [[305  12]
  [  6  17]]

 [[335   0]
  [  4   1]]

 [[339   0]
  [  1   0]]

 [[340   0]
  [  0   0]]

 [[338   0]
  [  2   0]]

 [[335   0]
  [  5   0]]

 [[338   0]
  [  0   2]]

 [[339   0]
  [  1   0]]

 [[336   0]
  [  3   1]]

 [[338   0]
  [  2   0]]

 [[335   2]
  [  2   1]]

 [[337   1]
  [  1   1]]

 [[335   0]
  [  3   2]]

 [[329   2]
  [  8   1]]

 [[337   2]
  [  0   1]]

 [[330   3]
  [  5   2]]

 [[331   1]
  [  8   0]]

 [[334   3]
  [  2   1]]

 [[314  13]
  [  8   5]]

 [[317   8]
  [  8   7]]

 [[340   0]
  [  0   0]]

 [[336   1]
  [  3   0]]

 [[340   0]
  [  0   0]]

 [[337   2]
  [  1   0]]

 [[340   0]
  [  0   0]]

 [[338   2]
  [  0   0]]

 [[340   0]
  [  0   0]]

 [[337   0]
  [  2   1]]

 [[340   0]
  [  0   0]]

 [[340   0]
  [  0   0]]

 [[338   2]
  [  0   0]]

 [[340   0]
  [  0   0]]

 [[340   0]
  [  0   0]]

 [[340   0]
  [  0   0]]

 [[339   0]
  [  1   0]]

 [[336   1]


/Users/jochem/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator MultiLabelBinarizer from version 1.5.1 when using version 1.1.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


AttributeError: 'str' object has no attribute 'get_position'

<Figure size 1000x3800 with 190 Axes>

In [6]:
pipeline.evaluation["hamming_loss"]
y_pred = pipeline.error_analyzer.y_pred
y_true = pipeline.error_analyzer.y_true
np.savez("../predictions.npz",y_pred = y_pred,y_true=y_true)


In [ ]:
# kernels = ["rbf", "linear", "sigmoid","poly"]
# c_values = np.linspace(start=1,stop=5,num=15)

kernels = ["rbf"]#, "linear", "sigmoid","poly"]
c_values = np.linspace(start=1,stop=5,num=15)
print(c_values)
bestf1 = 0
best_params = {}
for c in c_values:
    for k in kernels:
        print(f"Using {k} with a C of {c}:")
        model = SVM(kernel=k, C=c, class_weight = "balanced")
        pipeline = Pipeline(model=model, preprocessor=preprocess)
        pipeline.run()
        samp_avg_f1 = pipeline.evaluation["classification_report"]["samples avg"]["f1-score"]
        if samp_avg_f1 > bestf1:
            best_params = {"C":c, "kernel":k}
            bestf1 = samp_avg_f1


[1.         1.28571429 1.57142857 1.85714286 2.14285714 2.42857143
 2.71428571 3.         3.28571429 3.57142857 3.85714286 4.14285714
 4.42857143 4.71428571 5.        ]
Using rbf with a C of 1.0:
PREPROCESSED THE DATA
FIT THE DATA
MAKING PREDICTIONS
COMPLETED PREDICTIONS
              precision    recall  f1-score  support
micro avg      0.298476  0.582432  0.394689    740.0
macro avg      0.221152  0.320052  0.233527    740.0
weighted avg   0.339679  0.582432  0.403777    740.0
samples avg    0.366657  0.606082  0.413526    740.0
COMPLETED EVAL
Using rbf with a C of 1.2857142857142856:
PREPROCESSED THE DATA
FIT THE DATA
MAKING PREDICTIONS
COMPLETED PREDICTIONS
              precision    recall  f1-score  support
micro avg      0.324645  0.555405  0.409771    740.0
macro avg      0.248158  0.307645  0.241029    740.0
weighted avg   0.371481  0.555405  0.414053    740.0
samples avg    0.386366  0.581789  0.421104    740.0
COMPLETED EVAL
Using rbf with a C of 1.5714285714285714:
PREPROCE

In [ ]:
print(best_params)
print(bestf1)

{'C': 1.5714285714285714, 'kernel': 'rbf'}
0.42185317517929977


In [ ]:
kernels = ["rbf", "linear", "sigmoid","poly"]
c_values = np.linspace(start=1,stop=5,num=15)
print(c_values)
preprocess = Preprocessor()
preprocess.tfidf(min_df=0.01, max_df=0.35)
preprocess.split()

for kernel in kernels:
    for c in c_values:
        print(f"Using {kernel} with a C of {c}:")
        model = SVM(kernel=kernel, C=c, class_weight="balanced")
        pipeline=Pipeline(model=model,preprocessor=preprocess)
        pipeline.run()


[ 0.1    2.575  5.05   7.525 10.   ]
Using rbf with a C of 0.1:
PREPROCESSED THE DATA
FIT THE DATA
MAKING PREDICTIONS
COMPLETED PREDICTIONS
              precision    recall  f1-score  support
micro avg      0.187065  0.617568  0.287150    740.0
macro avg      0.171617  0.374091  0.191186    740.0
weighted avg   0.234162  0.617568  0.309181    740.0
samples avg    0.225527  0.640235  0.305116    740.0
COMPLETED EVAL
Using rbf with a C of 2.575:
PREPROCESSED THE DATA
FIT THE DATA
MAKING PREDICTIONS
COMPLETED PREDICTIONS
              precision    recall  f1-score  support
micro avg      0.597015  0.216216  0.317460    740.0
macro avg      0.212073  0.096733  0.124021    740.0
weighted avg   0.412187  0.216216  0.264776    740.0
samples avg    0.327721  0.260277  0.272402    740.0
COMPLETED EVAL
Using rbf with a C of 5.05:
PREPROCESSED THE DATA
FIT THE DATA
MAKING PREDICTIONS
COMPLETED PREDICTIONS
              precision    recall  f1-score  support
micro avg      0.635246  0.209459  0.3

In [ ]:
# from sklearn.multioutput import MultiOutputClassifier
# preprocess = Preprocessor()
# preprocess.tfidf(min_df=0.01, max_df=0.35)
# preprocess.split()

# kernels = ["rbf", "linear"]#, "sigmoid","poly"]
# c_values = np.linspace(start=0.1,stop=1,num=2)
# print(c_values)
# params = {"estimator__kernel":kernels,"estimator__C":c_values}
# scorer = make_scorer(f1_score, average="samples")



# model = MultiOutputClassifier(SVC(class_weight="balanced"))
# svc_cv = GridSearchCV(model,params,scoring=scorer)

AttributeError: 'Preprocessor' object has no attribute 'set_tfidf'

In [ ]:
X,y = preprocess.preprocess()
svc_cv.fit(X["train"],y["train"])

/opt/anaconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py:540: FitFailedWarning: 
4 fits failed out of a total of 20.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/multioutput.py", line 543, in fit
    super().fit(X, Y, sample_weight=sample_weight, **fit_params)
  File "/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
         

GridSearchCV(estimator=MultiOutputClassifier(estimator=SVC(class_weight='balanced')),
             param_grid={'estimator__C': array([0.1, 1. ]),
                         'estimator__kernel': ['rbf', 'linear']},
             scoring=make_scorer(f1_score, response_method='predict', average=samples))

In [ ]:
print(svc_cv.best_score_)

nan


In [ ]:
gptsummary= """The article, "Russia Prepares For A War With NATO," discusses Russia’s preparations for a long-term confrontation with NATO and Western nations. Key points include:

Russian Military Buildup: Russia is reportedly doubling its forces along its borders with NATO countries, including Finland, Estonia, Lithuania, and Latvia. This signals anticipation of potential conflict within the next decade.

Western Military Response: Western nations, particularly NATO members, are ramping up military spending and troop deployments. The Baltic States have increased defense budgets, and Germany plans to permanently station 4,800 combat-ready troops in the region by 2027.

Ukraine’s Influence on Conflict: Russia’s focus on Ukraine diminishes the likelihood of an immediate attack on NATO but underscores the need for NATO to remain prepared. A stronger Western military presence is deemed essential to deter potential aggression.

Risk of Escalation: Russia has warned that NATO’s military aid to Ukraine, particularly lethal support, risks provoking a broader conflict. However, despite these warnings, Russia has not directly attacked NATO.

Outlook for Ukraine: Russia’s ability to supply its forces outweighs Ukraine’s capabilities. The article notes that continued or increased Western support is critical for Ukraine to shift the dynamics on the battlefield.

The overall theme emphasizes heightened tensions and military posturing, with both sides preparing for potential escalation while striving to maintain deterrence."""

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

model = SVM(kernel = "rbf", C=3, class_weight ="balanced")
preprocess = Preprocessor()
preprocess.tfidf(min_df=0.01, max_df=0.35)
preprocess.split()


pipeline = Pipeline(model=model, preprocessor=preprocess)
pipeline.run()



PREPROCESSED THE DATA
FIT THE DATA
MAKING PREDICTIONS
COMPLETED PREDICTIONS
              precision    recall  f1-score  support
micro avg      0.607004  0.210811  0.312939    740.0
macro avg      0.212470  0.093854  0.121685    740.0
weighted avg   0.417561  0.210811  0.261778    740.0
samples avg    0.319947  0.251894  0.264435    740.0
COMPLETED EVAL


In [ ]:
import pandas as pd
xtest = preprocess.vectorizer.transform([gptsummary])

y_pred = model.predict(xtest)
print(y_pred)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
from typing import Counter



